/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsDeriveIndexRouteImport } from './routes/apps.derive/index'
import { Route as AppsDeriveHelpIndexRouteImport } from './routes/apps.derive.help/index'
import { Route as AppsDeriveLegalTermsIndexRouteImport } from './routes/apps.derive.legal.terms/index'
import { Route as AppsDeriveLegalPrivacyIndexRouteImport } from './routes/apps.derive.legal.privacy/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDeriveIndexRoute = AppsDeriveIndexRouteImport.update({
  id: '/apps/derive/',
  path: '/apps/derive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDeriveHelpIndexRoute = AppsDeriveHelpIndexRouteImport.update({
  id: '/apps/derive/help/',
  path: '/apps/derive/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDeriveLegalTermsIndexRoute =
  AppsDeriveLegalTermsIndexRouteImport.update({
    id: '/apps/derive/legal/terms/',
    path: '/apps/derive/legal/terms/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsDeriveLegalPrivacyIndexRoute =
  AppsDeriveLegalPrivacyIndexRouteImport.update({
    id: '/apps/derive/legal/privacy/',
    path: '/apps/derive/legal/privacy/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/derive': typeof AppsDeriveIndexRoute
  '/apps/derive/help': typeof AppsDeriveHelpIndexRoute
  '/apps/derive/legal/privacy': typeof AppsDeriveLegalPrivacyIndexRoute
  '/apps/derive/legal/terms': typeof AppsDeriveLegalTermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/derive': typeof AppsDeriveIndexRoute
  '/apps/derive/help': typeof AppsDeriveHelpIndexRoute
  '/apps/derive/legal/privacy': typeof AppsDeriveLegalPrivacyIndexRoute
  '/apps/derive/legal/terms': typeof AppsDeriveLegalTermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/derive/': typeof AppsDeriveIndexRoute
  '/apps/derive/help/': typeof AppsDeriveHelpIndexRoute
  '/apps/derive/legal/privacy/': typeof AppsDeriveLegalPrivacyIndexRoute
  '/apps/derive/legal/terms/': typeof AppsDeriveLegalTermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/derive'
    | '/apps/derive/help'
    | '/apps/derive/legal/privacy'
    | '/apps/derive/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps/derive'
    | '/apps/derive/help'
    | '/apps/derive/legal/privacy'
    | '/apps/derive/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/apps/derive/'
    | '/apps/derive/help/'
    | '/apps/derive/legal/privacy/'
    | '/apps/derive/legal/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsDeriveIndexRoute: typeof AppsDeriveIndexRoute
  AppsDeriveHelpIndexRoute: typeof AppsDeriveHelpIndexRoute
  AppsDeriveLegalPrivacyIndexRoute: typeof AppsDeriveLegalPrivacyIndexRoute
  AppsDeriveLegalTermsIndexRoute: typeof AppsDeriveLegalTermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/': {
      id: '/apps/derive/'
      path: '/apps/derive'
      fullPath: '/apps/derive'
      preLoaderRoute: typeof AppsDeriveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/help/': {
      id: '/apps/derive/help/'
      path: '/apps/derive/help'
      fullPath: '/apps/derive/help'
      preLoaderRoute: typeof AppsDeriveHelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/legal/terms/': {
      id: '/apps/derive/legal/terms/'
      path: '/apps/derive/legal/terms'
      fullPath: '/apps/derive/legal/terms'
      preLoaderRoute: typeof AppsDeriveLegalTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/legal/privacy/': {
      id: '/apps/derive/legal/privacy/'
      path: '/apps/derive/legal/privacy'
      fullPath: '/apps/derive/legal/privacy'
      preLoaderRoute: typeof AppsDeriveLegalPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsDeriveIndexRoute: AppsDeriveIndexRoute,
  AppsDeriveHelpIndexRoute: AppsDeriveHelpIndexRoute,
  AppsDeriveLegalPrivacyIndexRoute: AppsDeriveLegalPrivacyIndexRoute,
  AppsDeriveLegalTermsIndexRoute: AppsDeriveLegalTermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
