/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsTaplingIndexRouteImport } from './routes/apps.tapling/index'
import { Route as AppsKairosIndexRouteImport } from './routes/apps.kairos/index'
import { Route as AppsDeriveIndexRouteImport } from './routes/apps.derive/index'
import { Route as AppsKairosHelpIndexRouteImport } from './routes/apps.kairos.help/index'
import { Route as AppsDeriveHelpIndexRouteImport } from './routes/apps.derive.help/index'
import { Route as AppsKairosLegalTermsIndexRouteImport } from './routes/apps.kairos.legal.terms/index'
import { Route as AppsKairosLegalPrivacyIndexRouteImport } from './routes/apps.kairos.legal.privacy/index'
import { Route as AppsDeriveLegalTermsIndexRouteImport } from './routes/apps.derive.legal.terms/index'
import { Route as AppsDeriveLegalPrivacyIndexRouteImport } from './routes/apps.derive.legal.privacy/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTaplingIndexRoute = AppsTaplingIndexRouteImport.update({
  id: '/apps/tapling/',
  path: '/apps/tapling/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsKairosIndexRoute = AppsKairosIndexRouteImport.update({
  id: '/apps/kairos/',
  path: '/apps/kairos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDeriveIndexRoute = AppsDeriveIndexRouteImport.update({
  id: '/apps/derive/',
  path: '/apps/derive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsKairosHelpIndexRoute = AppsKairosHelpIndexRouteImport.update({
  id: '/apps/kairos/help/',
  path: '/apps/kairos/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDeriveHelpIndexRoute = AppsDeriveHelpIndexRouteImport.update({
  id: '/apps/derive/help/',
  path: '/apps/derive/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsKairosLegalTermsIndexRoute =
  AppsKairosLegalTermsIndexRouteImport.update({
    id: '/apps/kairos/legal/terms/',
    path: '/apps/kairos/legal/terms/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsKairosLegalPrivacyIndexRoute =
  AppsKairosLegalPrivacyIndexRouteImport.update({
    id: '/apps/kairos/legal/privacy/',
    path: '/apps/kairos/legal/privacy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsDeriveLegalTermsIndexRoute =
  AppsDeriveLegalTermsIndexRouteImport.update({
    id: '/apps/derive/legal/terms/',
    path: '/apps/derive/legal/terms/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsDeriveLegalPrivacyIndexRoute =
  AppsDeriveLegalPrivacyIndexRouteImport.update({
    id: '/apps/derive/legal/privacy/',
    path: '/apps/derive/legal/privacy/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/derive/': typeof AppsDeriveIndexRoute
  '/apps/kairos/': typeof AppsKairosIndexRoute
  '/apps/tapling/': typeof AppsTaplingIndexRoute
  '/apps/derive/help/': typeof AppsDeriveHelpIndexRoute
  '/apps/kairos/help/': typeof AppsKairosHelpIndexRoute
  '/apps/derive/legal/privacy/': typeof AppsDeriveLegalPrivacyIndexRoute
  '/apps/derive/legal/terms/': typeof AppsDeriveLegalTermsIndexRoute
  '/apps/kairos/legal/privacy/': typeof AppsKairosLegalPrivacyIndexRoute
  '/apps/kairos/legal/terms/': typeof AppsKairosLegalTermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/derive': typeof AppsDeriveIndexRoute
  '/apps/kairos': typeof AppsKairosIndexRoute
  '/apps/tapling': typeof AppsTaplingIndexRoute
  '/apps/derive/help': typeof AppsDeriveHelpIndexRoute
  '/apps/kairos/help': typeof AppsKairosHelpIndexRoute
  '/apps/derive/legal/privacy': typeof AppsDeriveLegalPrivacyIndexRoute
  '/apps/derive/legal/terms': typeof AppsDeriveLegalTermsIndexRoute
  '/apps/kairos/legal/privacy': typeof AppsKairosLegalPrivacyIndexRoute
  '/apps/kairos/legal/terms': typeof AppsKairosLegalTermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/derive/': typeof AppsDeriveIndexRoute
  '/apps/kairos/': typeof AppsKairosIndexRoute
  '/apps/tapling/': typeof AppsTaplingIndexRoute
  '/apps/derive/help/': typeof AppsDeriveHelpIndexRoute
  '/apps/kairos/help/': typeof AppsKairosHelpIndexRoute
  '/apps/derive/legal/privacy/': typeof AppsDeriveLegalPrivacyIndexRoute
  '/apps/derive/legal/terms/': typeof AppsDeriveLegalTermsIndexRoute
  '/apps/kairos/legal/privacy/': typeof AppsKairosLegalPrivacyIndexRoute
  '/apps/kairos/legal/terms/': typeof AppsKairosLegalTermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/derive/'
    | '/apps/kairos/'
    | '/apps/tapling/'
    | '/apps/derive/help/'
    | '/apps/kairos/help/'
    | '/apps/derive/legal/privacy/'
    | '/apps/derive/legal/terms/'
    | '/apps/kairos/legal/privacy/'
    | '/apps/kairos/legal/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps/derive'
    | '/apps/kairos'
    | '/apps/tapling'
    | '/apps/derive/help'
    | '/apps/kairos/help'
    | '/apps/derive/legal/privacy'
    | '/apps/derive/legal/terms'
    | '/apps/kairos/legal/privacy'
    | '/apps/kairos/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/apps/derive/'
    | '/apps/kairos/'
    | '/apps/tapling/'
    | '/apps/derive/help/'
    | '/apps/kairos/help/'
    | '/apps/derive/legal/privacy/'
    | '/apps/derive/legal/terms/'
    | '/apps/kairos/legal/privacy/'
    | '/apps/kairos/legal/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsDeriveIndexRoute: typeof AppsDeriveIndexRoute
  AppsKairosIndexRoute: typeof AppsKairosIndexRoute
  AppsTaplingIndexRoute: typeof AppsTaplingIndexRoute
  AppsDeriveHelpIndexRoute: typeof AppsDeriveHelpIndexRoute
  AppsKairosHelpIndexRoute: typeof AppsKairosHelpIndexRoute
  AppsDeriveLegalPrivacyIndexRoute: typeof AppsDeriveLegalPrivacyIndexRoute
  AppsDeriveLegalTermsIndexRoute: typeof AppsDeriveLegalTermsIndexRoute
  AppsKairosLegalPrivacyIndexRoute: typeof AppsKairosLegalPrivacyIndexRoute
  AppsKairosLegalTermsIndexRoute: typeof AppsKairosLegalTermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/tapling/': {
      id: '/apps/tapling/'
      path: '/apps/tapling'
      fullPath: '/apps/tapling/'
      preLoaderRoute: typeof AppsTaplingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/kairos/': {
      id: '/apps/kairos/'
      path: '/apps/kairos'
      fullPath: '/apps/kairos/'
      preLoaderRoute: typeof AppsKairosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/': {
      id: '/apps/derive/'
      path: '/apps/derive'
      fullPath: '/apps/derive/'
      preLoaderRoute: typeof AppsDeriveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/kairos/help/': {
      id: '/apps/kairos/help/'
      path: '/apps/kairos/help'
      fullPath: '/apps/kairos/help/'
      preLoaderRoute: typeof AppsKairosHelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/help/': {
      id: '/apps/derive/help/'
      path: '/apps/derive/help'
      fullPath: '/apps/derive/help/'
      preLoaderRoute: typeof AppsDeriveHelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/kairos/legal/terms/': {
      id: '/apps/kairos/legal/terms/'
      path: '/apps/kairos/legal/terms'
      fullPath: '/apps/kairos/legal/terms/'
      preLoaderRoute: typeof AppsKairosLegalTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/kairos/legal/privacy/': {
      id: '/apps/kairos/legal/privacy/'
      path: '/apps/kairos/legal/privacy'
      fullPath: '/apps/kairos/legal/privacy/'
      preLoaderRoute: typeof AppsKairosLegalPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/legal/terms/': {
      id: '/apps/derive/legal/terms/'
      path: '/apps/derive/legal/terms'
      fullPath: '/apps/derive/legal/terms/'
      preLoaderRoute: typeof AppsDeriveLegalTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/derive/legal/privacy/': {
      id: '/apps/derive/legal/privacy/'
      path: '/apps/derive/legal/privacy'
      fullPath: '/apps/derive/legal/privacy/'
      preLoaderRoute: typeof AppsDeriveLegalPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsDeriveIndexRoute: AppsDeriveIndexRoute,
  AppsKairosIndexRoute: AppsKairosIndexRoute,
  AppsTaplingIndexRoute: AppsTaplingIndexRoute,
  AppsDeriveHelpIndexRoute: AppsDeriveHelpIndexRoute,
  AppsKairosHelpIndexRoute: AppsKairosHelpIndexRoute,
  AppsDeriveLegalPrivacyIndexRoute: AppsDeriveLegalPrivacyIndexRoute,
  AppsDeriveLegalTermsIndexRoute: AppsDeriveLegalTermsIndexRoute,
  AppsKairosLegalPrivacyIndexRoute: AppsKairosLegalPrivacyIndexRoute,
  AppsKairosLegalTermsIndexRoute: AppsKairosLegalTermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
