/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowMainSplashIndexRouteImport } from './routes/window.main.splash/index'
import { Route as WindowMainHomeIndexRouteImport } from './routes/window.main.home/index'
import { Route as WindowMainAboutIndexRouteImport } from './routes/window.main.about/index'

const WindowMainSplashIndexRoute = WindowMainSplashIndexRouteImport.update({
  id: '/window/main/splash/',
  path: '/window/main/splash/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainHomeIndexRoute = WindowMainHomeIndexRouteImport.update({
  id: '/window/main/home/',
  path: '/window/main/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainAboutIndexRoute = WindowMainAboutIndexRouteImport.update({
  id: '/window/main/about/',
  path: '/window/main/about/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/window/main/about/': typeof WindowMainAboutIndexRoute
  '/window/main/home/': typeof WindowMainHomeIndexRoute
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
}
export interface FileRoutesByTo {
  '/window/main/about': typeof WindowMainAboutIndexRoute
  '/window/main/home': typeof WindowMainHomeIndexRoute
  '/window/main/splash': typeof WindowMainSplashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/window/main/about/': typeof WindowMainAboutIndexRoute
  '/window/main/home/': typeof WindowMainHomeIndexRoute
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/window/main/about/'
    | '/window/main/home/'
    | '/window/main/splash/'
  fileRoutesByTo: FileRoutesByTo
  to: '/window/main/about' | '/window/main/home' | '/window/main/splash'
  id:
    | '__root__'
    | '/window/main/about/'
    | '/window/main/home/'
    | '/window/main/splash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WindowMainAboutIndexRoute: typeof WindowMainAboutIndexRoute
  WindowMainHomeIndexRoute: typeof WindowMainHomeIndexRoute
  WindowMainSplashIndexRoute: typeof WindowMainSplashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window/main/splash/': {
      id: '/window/main/splash/'
      path: '/window/main/splash'
      fullPath: '/window/main/splash/'
      preLoaderRoute: typeof WindowMainSplashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/home/': {
      id: '/window/main/home/'
      path: '/window/main/home'
      fullPath: '/window/main/home/'
      preLoaderRoute: typeof WindowMainHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main/about/': {
      id: '/window/main/about/'
      path: '/window/main/about'
      fullPath: '/window/main/about/'
      preLoaderRoute: typeof WindowMainAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WindowMainAboutIndexRoute: WindowMainAboutIndexRoute,
  WindowMainHomeIndexRoute: WindowMainHomeIndexRoute,
  WindowMainSplashIndexRoute: WindowMainSplashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
