[package]
name = "roxmltree-api"
version = "0.0.1"
description = ""
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]
name = "roxmltree_api"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"
path = "src/bin/cli.rs"
required-features = ["cli"]

[features]
default = []
cli = ["dep:clap", "specta/export"]
console_log = ["dep:console_error_panic_hook"]
tracing = ["console_log"]

[dependencies]

# Bindgen
wasm-bindgen = "0.2.92"
js-sys = "0.3.69"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6.5"
specta = { workspace = true, features = ["typescript", "serde"] }

# cli (feature)
clap = { version = "4.5.7", features = ["derive"], optional = true }

# console_log (feature)
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.42"

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort" # Without console_error_panic_hook in debug mode, the panic's stack trace is useless anway
