/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbeddedRouteRouteImport } from './routes/embedded/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as EmbeddedIndexRouteImport } from './routes/embedded/index'
import { Route as AuthSessionTokenIndexRouteImport } from './routes/auth.session-token/index'
import { Route as EmbeddedAdditionalIndexRouteImport } from './routes/embedded.additional/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedRouteRoute = EmbeddedRouteRouteImport.update({
  id: '/embedded',
  path: '/embedded',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedIndexRoute = EmbeddedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmbeddedRouteRoute,
} as any)
const AuthSessionTokenIndexRoute = AuthSessionTokenIndexRouteImport.update({
  id: '/auth/session-token/',
  path: '/auth/session-token/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedAdditionalIndexRoute = EmbeddedAdditionalIndexRouteImport.update({
  id: '/additional/',
  path: '/additional/',
  getParentRoute: () => EmbeddedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embedded': typeof EmbeddedRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/embedded/': typeof EmbeddedIndexRoute
  '/auth/session-token/': typeof AuthSessionTokenIndexRoute
  '/embedded/additional/': typeof EmbeddedAdditionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/embedded': typeof EmbeddedIndexRoute
  '/auth/session-token': typeof AuthSessionTokenIndexRoute
  '/embedded/additional': typeof EmbeddedAdditionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embedded': typeof EmbeddedRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/embedded/': typeof EmbeddedIndexRoute
  '/auth/session-token/': typeof AuthSessionTokenIndexRoute
  '/embedded/additional/': typeof EmbeddedAdditionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embedded'
    | '/api/$'
    | '/embedded/'
    | '/auth/session-token/'
    | '/embedded/additional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/embedded'
    | '/auth/session-token'
    | '/embedded/additional'
  id:
    | '__root__'
    | '/'
    | '/embedded'
    | '/api/$'
    | '/embedded/'
    | '/auth/session-token/'
    | '/embedded/additional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbeddedRouteRoute: typeof EmbeddedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AuthSessionTokenIndexRoute: typeof AuthSessionTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded': {
      id: '/embedded'
      path: '/embedded'
      fullPath: '/embedded'
      preLoaderRoute: typeof EmbeddedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/': {
      id: '/embedded/'
      path: '/'
      fullPath: '/embedded/'
      preLoaderRoute: typeof EmbeddedIndexRouteImport
      parentRoute: typeof EmbeddedRouteRoute
    }
    '/auth/session-token/': {
      id: '/auth/session-token/'
      path: '/auth/session-token'
      fullPath: '/auth/session-token/'
      preLoaderRoute: typeof AuthSessionTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/additional/': {
      id: '/embedded/additional/'
      path: '/additional'
      fullPath: '/embedded/additional/'
      preLoaderRoute: typeof EmbeddedAdditionalIndexRouteImport
      parentRoute: typeof EmbeddedRouteRoute
    }
  }
}

interface EmbeddedRouteRouteChildren {
  EmbeddedIndexRoute: typeof EmbeddedIndexRoute
  EmbeddedAdditionalIndexRoute: typeof EmbeddedAdditionalIndexRoute
}

const EmbeddedRouteRouteChildren: EmbeddedRouteRouteChildren = {
  EmbeddedIndexRoute: EmbeddedIndexRoute,
  EmbeddedAdditionalIndexRoute: EmbeddedAdditionalIndexRoute,
}

const EmbeddedRouteRouteWithChildren = EmbeddedRouteRoute._addFileChildren(
  EmbeddedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbeddedRouteRoute: EmbeddedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthSessionTokenIndexRoute: AuthSessionTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
